#!/bin/ruby
require "shodan"
require "resolv"
require "socket"
require "colorize"
require "net/http"
require "artii"

fish_art = Artii::Base.new :font => "big"
puts fish_art.asciify("Fishmap").light_green
if (ARGV[0].nil? || ARGV[1].nil? || ARGV[0] == "-h" || ARGV[0] == "--help") then
   puts "Usage: "
   puts "[ DNS resolver ] => --resolver <www.google.com>"
   puts "[ Port Scanner ] => --port-scan <ip>"
   puts "[ Shodan API   ] => --shodan <your api key> <service name>"
   puts "[ Dir Brute    ] => --dir-brute <http://www.vulnweb.com>"
end

if (ARGV[0] == "--dir-brute")
   File.open("dir.txt").each do | dir |
      begin
         url = (ARGV[1]+"/"+dir.chomp)
         request = Net::HTTP.get_response(URI.parse(url))
         puts request.code+" => "+dir
      rescue URI::InvalidURIError
         puts "please enter the URL as the program accepts....".white
         break
      rescue Interrupt
         puts ""
         puts "Program stopped by user".light_red
         break
      end
   end
elsif (ARGV[0] == "--port-scan")
   ports = [20,21,22,23,25,80,110,443,512,522,8080,1080,4444,3389]
   ports.each do | port |
      begin
         sock = TCPSocket.new(ARGV[1],port)
         printf "[ * ] ".light_yellow
         puts "Port: #{port} Open!".light_green
      rescue Errno::ECONNREFUSED
         printf "[ * ] ".light_yellow
         puts "Port: #{port} Closed".light_red
      rescue Interrupt
         puts ""
         puts "Program stopped by user".light_red
         break
       end
   end
elsif (ARGV[0] == "--resolver")
   puts Resolv.getaddresses "#{ARGV[1]}"
elsif (ARGV[0] == "--shodan")
   begin
      api_key = Shodan::Shodan.new(ARGV[1])

      results = api_key.search(ARGV[2])
      results['matches'].each do |r|
         puts "IP: #{r['ip_str']}"
         puts r['data'] + "\n" + "="*45
      end
   rescue JSON::ParserError
      puts "API Key invalid!".light_red
   end
end
